INSERT INTO brand_picture (brand_id, url, is_main, type) VALUES 
(4, '/assets/images/landingImage/cartier/landing_collection_cartier.jpg', 0, 'slide'),
(3, '/assets/images/landingImage/chanel/landing_collection_chanel.jpg', 0, 'slide'),
(7, '/assets/images/landingImage/dior/landing_collection_dior.jpg', 0, 'slide'),
(10, '/assets/images/landingImage/gucci/landing_caroussel_gucci.jpeg', 0, 'slide'),
(10, '/assets/images/landingImage/gucci/landing_collection_gucci.jpg', 0, 'slide'),
(5, '/assets/images/landingImage/guerlain/landing_caroussel_guerlain.jpeg', 0, 'slide'),
(5, '/assets/images/landingImage/guerlain/landing_collection_guerlain.jpg', 0, 'slide'),
(2, '/assets/images/landingImage/hermes/landing_collection_hermes.jpg', 0, 'slide'),
(9, '/assets/images/landingImage/louisvuitton/landing_bg_2.jpeg', 0, 'slide'),
(9, '/assets/images/landingImage/louisvuitton/landing_collection_louisvuitton.jpg', 0, 'slide'),
(8, '/assets/images/landingImage/prada/landing_collection_prada.jpg', 0, 'slide'),
(1, '/assets/images/landingImage/rolex/landing_bg_3.jpeg', 0, 'slide'),
(1, '/assets/images/landingImage/rolex/landing_caroussel_rolex.jpeg', 0, 'slide'),
(1, '/assets/images/landingImage/rolex/landing_collection_rolex.jpg', 0, 'slide'),
(6, '/assets/images/landingImage/ysl/landing_bg_1.jpeg', 0, 'slide'),
(6, '/assets/images/landingImage/ysl/landing_collection_ysl.jpg', 0, 'slide');